name: Update List
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x task.sh
          sudo ./task.sh
      - name: Refresh cache
        run: curl -sS https://purge.jsdelivr.net/gh/dream10201/stash-rule@master/proxy-rule.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
